# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow when you push to the main branch
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions needed to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js to install dependencies and run the build command
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project (npm run build)
        run: npm run build

      # Configure GitHub Pages deployment environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Uploads the built static files (from the 'dist' directory)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # The directory that Vite builds your project into

      # Deploys the artifact to the live GitHub Pages site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4